Repository FuelLabs/forc-wallet, pull requests merged in 2022-10, with the labels that each got.

#55 bump version to 0.1.2
  Cargo.lock
  Cargo.toml
Labels: release

#57 test/refactor: Add tests for existing wallet operations and split CLI and the actual logic
  Cargo.lock
  Cargo.toml
  src/account.rs
  src/export.rs
  src/import.rs
  src/init.rs
  src/list.rs
  src/main.rs
  src/sign.rs
  src/utils.rs
Labels: enhancement

#58 import is own command and not anymore a argument
  README.md
Labels: documentation
