Repository FuelLabs/forc-wallet, pull requests merged in 2022-09, with the labels that each got.

#42 Adds a CI check to ensure the lock file is always up to date
  .github/workflows/ci.yml
Labels: code quality

#40 feat: Add --export to account to export account's private key
  src/account.rs
  src/main.rs
Labels: enhancement

#47 feat: Moved --export to a seperate export command
  src/account.rs
  src/export.rs
  src/main.rs
Labels: enhancement

#50 refactor: Use SDK derivation path
  src/account.rs
  src/utils.rs
Labels: code quality

#48 Bump version to v0.1.1
  Cargo.lock
  Cargo.toml
Labels: release

#54 Fix error in the case of an non-existing vault path and refactor discrete string utility
  src/export.rs
  src/import.rs
  src/init.rs
  src/main.rs
  src/utils.rs
Labels: bug
