Repository FuelLabs/forc-wallet, pull requests merged in 2023-02, with the labels that each got.

#74 chore: 1.67.0 cargo clippy fix
  src/account.rs
  src/export.rs
  src/init.rs
  src/list.rs
  src/utils.rs
Labels: code quality

#79 Refactor `--path` arg for commands, use consistent terminology for wallet directory
  README.md
  src/account.rs
  src/export.rs
  src/import.rs
  src/init.rs
  src/list.rs
  src/main.rs
  src/sign.rs
  src/utils.rs
Labels: enhancement, code quality

#80 Expect path to wallet file, not dir. Use a cache for account addresses.
  Cargo.lock
  Cargo.toml
  README.md
  src/account.rs
  src/export.rs
  src/import.rs
  src/init.rs
  src/list.rs
  src/main.rs
  src/sign.rs
  src/utils.rs
Labels: enhancement, code quality

#81 Update all dependencies, removed unused
  Cargo.lock
  Cargo.toml
  src/init.rs
  src/sign.rs
  src/utils.rs
Labels: code quality

#84 Address ambiguitiy in init, new, list. Create a new `account` subcommand
  README.md
  src/account.rs
  src/export.rs
  src/import.rs
  src/init.rs
  src/main.rs
  src/new.rs
  src/sign.rs
  src/utils.rs
Labels: enhancement, code quality

#85 Add `--unverified` option to commands that display cached addresses
  src/account.rs
  src/main.rs
Labels: enhancement

#88 feat: Add support for signing arbitrary data via new `string`, `file` or `hex` subcommands
  Cargo.lock
  Cargo.toml
  README.md
  src/account.rs
  src/main.rs
  src/sign.rs
  src/utils.rs
Labels: enhancement

#90 Publish v0.2.0
  Cargo.lock
  Cargo.toml
Labels: release

#93 feat: add support for displaying public key for an account derived with `forc-wallet`
  README.md
  src/account.rs
  src/main.rs
Labels: enhancement

#94 chore: bump version to 0.2.1
  Cargo.lock
  Cargo.toml
Labels: release
