Repository FuelLabs/forc-wallet, pull requests merged in 2023-07, with the labels that each got.

#116 chore: bump fuels-* to 0.43 and fuel-* to 0.31
  Cargo.lock
  Cargo.toml
  src/account.rs
  src/balance.rs
  src/import.rs
  src/new.rs
  src/sign.rs
  src/utils.rs
Labels: enhancement, code quality

#119 refactor: expose derive_secret_key functionality
  src/account.rs
Labels: code quality

#118 fix: plain address queries with as-hex flag fails
  src/account.rs
Labels: bug

#114 chore: bump version to 0.2.3
  Cargo.lock
  Cargo.toml
Labels: release

#120 refactor: expose balance collecting and printing functionality
  src/account.rs
  src/balance.rs
  src/lib.rs
Labels: enhancement

#125 feat: enforce 0x prefix for hex data input
  README.md
  src/sign.rs
Labels: enhancement

#126 fix: forc-wallet balance command panics after clap v4 update
  src/balance.rs
Labels: bug

#123 Bump fuels, fuels-core and fuel-* deps
  Cargo.lock
  Cargo.toml
Labels: blocked

#124 chore: bump version to v0.2.4
  Cargo.lock
  Cargo.toml
Labels: release
