Repository FuelLabs/forc-wallet, pull requests merged in 2024-10, with the labels that each got.

#210 feat: implement check sum reporting and update default target
  Cargo.lock
  Cargo.toml
  src/account.rs
  src/balance.rs
  src/lib.rs
  src/list.rs
  src/main.rs
Labels: enhancement, breaking

#213 chore: bump sdk to v0.66.9
  Cargo.lock
  Cargo.toml
Labels: dependencies

#214 chore: bump to 0.11.0
  Cargo.lock
  Cargo.toml
Labels: release

#220 Fix minor wallet issues
  .github/workflows/ci.yml
  .github/workflows/markdown-lint.yml
  .gitignore
  Cargo.lock
  Cargo.toml
  rust-toolchain.toml
  src/account.rs
  src/utils.rs
Labels: bug, testing

#221 chore: bump to 0.11.1
  Cargo.lock
  Cargo.toml
Labels: release
